version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis_1
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: always

volumes:
  redis-data: