spring:
  config:
    import: application-secret.yml

  datasource:
    url: jdbc:mysql://${custom.db.host}:3306/tung_db
    username: root
    password: ${custom.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false

  data:
    redis:
      host: redis_1
      port: 6379
      password: ${custom.db.password}
#    elasticsearch:
#      uris: http://${custom.db.host}:9200

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false

logging:
  level:
    com.example: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO

# 프로메테우스 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      access: unrestricted

custom:
  elastic:
    host: ${custom.db.host}
  site:
    domain: ${custom.prod.domain}
    backUrl: ${custom.prod.backUrl}
    frontUrl: ${custom.prod.frontUrl}
