server:
  port: 8080
  tomcat:
    max-swallow-size: 1GB
    max-http-form-post-size: 1GB

spring:
  output:
    ansi:
      enabled: always

  profiles:
    active: dev
    include: secret

  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: ${spring.servlet.multipart.max-request-size}

  jackson:
    serialization:
      fail-on-empty-beans: false

  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      auto-commit: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

  data:
    redis:
      host: localhost
      port: 6379

#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            clientId: ON_SECRET
#            scope: profile_nickname, profile_image
#            client-name: Kakao
#            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE

springdoc:
  default-produces-media-type: application/json;charset=UTF-8

custom:
  site:
    backUrl: "${custom.dev.backUrl}"
    frontUrl: "${custom.dev.frontUrl}"

  prod:
    domain: devapi.store
    backUrl: "https://api.${custom.prod.domain}"
    frontUrl: "https://www.${custom.prod.domain}"

  dev:
    domain: localhost
    backUrl: "http://${custom.dev.domain}:${server.port}"
    frontUrl: "http://${custom.dev.domain}:3000"

toss:
  client-key: "test_ck_5OWRapdA8dP5dB4NPlyB8o1zEqZK"
  secret-key: "test_sk_0RnYX2w532MB1mZpel9K8NeyqApQ"
